services:
  - type: web
    name: anime-bot-playwright
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: playwright install && python main.py
    envVars:
      - key: DISCORD_WEBHOOK
        sync: false